[tool.poetry]
name = "repl_python3_TODOBOT2"
version = "0.1.0"
description = ""
authors = ["astashinboris56 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "^2.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
